from multiprocessing import Process
import time

COUNT = 10_000_000_000
PROCCESS_COUNT = 16

def countdown(n):
    while n>0:
        n -= 1

if __name__ == '__main__':
    p1 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p2 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p3 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p4 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p5 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p6 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p7 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p8 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p9 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p10 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p11 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p12 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p13 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p14 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p15 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))
    p16 = Process(target=countdown, args=(COUNT//PROCCESS_COUNT,))

    start = time.time()

    print('Process 1 started')
    p1.start()
    print('Process 2 started')
    p2.start()
    print('Process 3 started')
    p3.start()
    print('Process 4 started')
    p4.start()
    print('Process 5 started')
    p5.start()
    print('Process 6 started')
    p6.start()
    print('Process 7 started')
    p7.start()
    print('Process 8 started')
    p8.start()
    print('Process 9 started')
    p9.start()
    print('Process 10 started')
    p10.start()
    print('Process 11 started')
    p11.start()
    print('Process 12 started')
    p12.start()
    print('Process 13 started')
    p13.start()
    print('Process 14 started')
    p14.start()
    print('Process 15 started')
    p15.start()
    print('Process 16 started')
    p16.start()

    # Join each process using a loop
    p1.join()
    print('Process 1 joined')
    p2.join()
    print('Process 2 joined')
    p3.join()
    print('Process 3 joined')
    p4.join()
    print('Process 4 joined')
    p5.join()
    print('Process 5 joined')
    p6.join()
    print('Process 6 joined')
    p7.join()
    print('Process 7 joined')
    p8.join()
    print('Process 8 joined')
    p9.join()
    print('Process 9 joined')
    p10.join()
    print('Process 10 joined')
    p11.join()
    print('Process 11 joined')
    p12.join()  
    print('Process 12 joined')
    p13.join()
    print('Process 13 joined')
    p14.join()
    print('Process 14 joined')
    p15.join()
    print('Process 15 joined')
    p16.join()
    print('Process 16 joined')

    end = time.time()

    print('Time taken in seconds -', end - start)